### ISSUE TITLE
Login to Beta channel but publishing to edge

### ISSUE THREAD

**Issue by baruchiro** [samuelmeuli/action-snapcraft#1]
Hi, I'm using this action, one step before [`action-electron-builder`](https://github.com/samuelmeuli/action-electron-builder).

I created a login key for `beta` channel, but the `electron-builder` from `action-electron-builder` trying to publish to `edge`.

[The check-suite](https://github.com/baruchiro/israeli-bank-scrapers-desktop/runs/348777326)
[4_Install Snapcraft.txt](https://github.com/samuelmeuli/action-snapcraft/files/3964160/4_Install.Snapcraft.txt)
[5_Buildrelease Electron app.txt](https://github.com/samuelmeuli/action-snapcraft/files/3964161/5_Buildrelease.Electron.app.txt)

**Comment by samuelmeuli** [comment]
That's outside the scope of this action, it's only responsible for installing and logging you in to Snapcraft. You'll probably have to configure Snapcraft or `electron-builder` to publish to `beta` instead.
