### ISSUE TITLE
Snapcraft needs Multipass to build

### ISSUE THREAD

**Issue by jimmyd-be** [samuelmeuli/action-snapcraft#12]
I'm trying to build a snap using Github action but when I do so I get following error:
You need 'multipass' set-up to build snaps: https://multipass.run.

Manually installing multipass is also not working because of some permissions inside the container.

**Comment by mahnunchik** [comment]
@jimmyd-be how did you fix the issue?

**Comment by jimmyd-be** [comment]
I didn't. I'm not using snaps anymore.
