### ISSUE TITLE
Unable to connect to the source LXD

### ISSUE THREAD

**Issue by pbek** [samuelmeuli/action-snapcraft#18]
Thank you for supporting my attempt to build Snaps for https://github.com/pbek/QOwnNotes on GithHub Actions! 😁 

I currently get a `Unable to connect to the source LXD` when trying to install snapcraft with LXD:

https://github.com/qownnotes/qon-build-test/runs/1139764378?check_suite_focus=true#step:8:20

Do you know a way to get around that or to build with multipass on GitHub Actions?

**Comment by casperdcl** [comment]
Maybe it's your `env` (https://github.com/qownnotes/qon-build-test/runs/1139764378?check_suite_focus=true#step:8:4)?

Works fine for me; I don't specify any `env` (https://github.com/casperdcl/cdcl/runs/1139113535?check_suite_focus=true#step:4:3)

**Comment by pbek** [comment]
Thank you. Really strange, I'll do some more tests.

**Comment by pbek** [comment]
No env any more, still the same error: https://github.com/qownnotes/qon-build-test/runs/1140967363?check_suite_focus=true#step:4:1 😢

**Comment by pbek** [comment]
I also tried `casperdcl/action-snapcraft@master`, like in your example.

Same result:
https://github.com/qownnotes/qon-build-test/runs/1140979298?check_suite_focus=true#step:4:1

**Comment by casperdcl** [comment]
Could you try `ubuntu-18.04` rather than `16.04`?

**Comment by pbek** [comment]
That's it. Thank you very much! I completely forgot I had to use Ubuntu 16.04 for the AppImage!
