### ISSUE TITLE
Add `use_lxd` option

### ISSUE THREAD

**Issue by casperdcl** [samuelmeuli/action-snapcraft#2]
`lxd` should be installed and set up as well by this action.

- `snapcraft` doesn't seem to be able to build anything as-is.
- installing `multipass` doesn't seem to work
  + [`launch failed: CPU does not support KVM extensions.`](https://github.com/casperdcl/cdcl/runs/447863764#step:5:8)
- installing `lxd` fixes this
  + (https://github.com/casperdcl/cdcl/commit/971e401e9ed728a59e6742ec0a728c6daf5b7e0f -> https://github.com/casperdcl/cdcl/runs/447883745#step:5:14)

**Comment by samuelmeuli** [comment]
I'm no expert in this area, but this seems like a good idea to me.

- [ ] Document that `multipass` is not supported in GitHub's VMs
- [ ] Get the action to install `lxd` (either by default or based on an option, depending on how much of an impact this has on build time)

Alternatively, it seems that the build should also be possible without a container (https://forum.snapcraft.io/t/multipass-on-raspberry-pi-3b/12162/6):

> for building snaps you can use an lxd container or a chroot with the SNAPCRAFT_BUILD_ENVIRONMENT=host env variable set. you can just not build them using multipass (which sadly became a default with snapcraft 3.x limiting building without prior tinkering on non x86 a lot).

**Comment by casperdcl** [comment]
yes it's odd that I couldn't find any official guidance on this. Will keep tinkering and submit a PR along those lines soon...

Interestingly my tests show `lxd` can take anywhere from ~1 to ~10min to setup.
