### ISSUE TITLE
Trouble getting SC token, what goes in SNAP_NAME ?

### ISSUE THREAD

**Issue by VictorioBerra** [samuelmeuli/action-snapcraft#21]
Im trying to do a first time deployment, not sure what to put for --snaps SNAP_NAME

**Comment by casperdcl** [comment]
whatever snap name you'd like to push to on https://snapcraft.io (e.g. https://snapcraft.io/tqdm would mean `--snaps tqdm`)

**Comment by VictorioBerra** [comment]
@casperdcl thanks for the quick reply.

Do I need to push my package first and then specify the name? 

![image](https://user-images.githubusercontent.com/2934507/99918436-6e4e8900-2cdc-11eb-82ac-a159bcb15361.png)

I can login just fine, but the export login command fails. This is on Ubuntu 20 on an EC2 instance I just spun up.

**Comment by casperdcl** [comment]
I guess you need to follow https://snapcraft.io/docs/using-the-snap-store
