### ISSUE TITLE
Support Ubuntu 20.04

### ISSUE THREAD

**Issue by casperdcl** [samuelmeuli/action-snapcraft#24]
Related #23

**Comment by ankurk91** [comment]
https://discuss.linuxcontainers.org/t/post-ubuntu-and-lxd-migration-get-http-unix-socket-1-0-dial-unix-var-lib-lxd-unix-socket-connect-no-such-file-or-directory/2067/3

**Comment by casperdcl** [comment]
Seems fixed in #40
