### ISSUE TITLE
snapcraft login broke starting June 15, 2022

### ISSUE THREAD

**Issue by ddennedy** [samuelmeuli/action-snapcraft#36]
From https://github.com/mltframework/shotcut/runs/6906541923?check_suite_focus=true, using version 1.2.0:

`--with is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead`

See related https://github.com/certbot/certbot/issues/9323

On a previous build, I got a different login failure "This login method is not longer supported." So, I thought I needed to re-export a token to my secrets, which I did but then got the above.

See snapcraft [updated doc](https://forum.snapcraft.io/t/snapcraft-authentication-options/30473) on the matter.

**Comment by Saviq** [comment]
+1, looks like the token should be removed from this action config and document that `SNAPCRAFT_STORE_CREDENTIALS` should be used where needed instead.

**Comment by ddennedy** [comment]
Thanks for the tip @Saviq
