### ISSUE TITLE
Please update the following actions to use Node.js 16: samuelmeuli/action-snapcraft@v1

### ISSUE THREAD

**Issue by ghost** [samuelmeuli/action-snapcraft#39]
i see in the source that it's been updates to node 16, but when I use the action it's still using node12.

i see https://github.com/casperdcl/action-snapcraft is still v12 and hes listed as the maintainer.

so maybe it's just a publishing thing.

**Comment by abulka** [comment]
Do we need to refer to `samuelmeuli/action-snapcraft@v2` perhaps?

**Comment by ghost** [comment]
im not sure what that is.

**Comment by abulka** [comment]
I tried referring to `v2` but it doesn't exist.

    Unable to resolve action `samuelmeuli/action-snapcraft@v2`, unable to find version `v2`

The solution is to `uses: samuelmeuli/action-snapcraft@master` to get the latest version.

**Comment by casperdcl** [comment]
fixed in `samuelmeuli/action-snapcraft@v2` now :)
